apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-dev
  namespace: jejuonul-dev
  labels:
    app: api-gateway-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway-dev
  template:
    metadata:
      labels:
        app: api-gateway-dev
    spec:
      containers:
      - name: api-gateway-dev
        image: jejuonul-api-dev.kr.ncr.ntruss.com/api-gateway-dev:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "1"
            memory: "2Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
      imagePullSecrets:
      - name: ncr-secret
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0%
    type: RollingUpdate
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-gateway-dev
  namespace: jejuonul-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-gateway-dev
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 90
